apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider-poc-hexagonal
  namespace: mayorista-models
spec:
  provider: aws
  secretObjects:
    - secretName: apikey-prod-inner-providers-mayorista
      type: Opeque
      data:
        - objectName: apiw-ibm-x-client-secret
          key: client-secret
  parameters:
    objects: |
      - objectName: "APIKey/prod/inner/providers/mayorista"
        objectType: secretsmanager
        jmesPath:
          - path: clientsecret
            objectAlias: apiw-ibm-x-client-secret