replicaCount: 1

serviceAccount: poc-hexagonal-dev-sa

# volumes:
#   list:
#   - name: secrets-store-inline
#     csi:
#       driver: secrets-store.csi.k8s.io
#       readOnly: true
#       volumeAttributes:
#         secretProviderClass: "secrets-provider-poc-hexagonal"

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

container:
  image:
    pullPolicy: Always
  ports:
    - name: http
      containerPort: 3000
      protocol: TCP

vars:
  enabled: true
  list:
    - name: NODE_ENV
      value: "quality"
    - name: PORT
      value: "3000"
    - name: BASE_PATH
      value: "/poc-hexagonal/v1"
    - name: REDIS_HOST
      value: localhost
    - name: REDIS_PORT
      value: 6379
    # - name: INNER_PROVIDER_X_CLIENT_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: apikey-qa-inner-providers-mayorista
    #       key: client-secret

secrets:
   
livenessEnabler: true
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

readinessEnabler: true
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

service:
  type: ClusterIP
  port: 3000

ingress:
  ingressClassName: ingress-internal
  enabled: true
  annotations:
    alb.ingress.kubernetes.io/target-type: 'ip'
    alb.ingress.kubernetes.io/group.name: inner-bcl
    alb.ingress.kubernetes.io/healthcheck-path: /health
  rules:
    host: pochexagonal-bcl-ms-qa.itauchile2.cl
    path: "/"

resources:
  limits:
    cpu: 300m
    memory: 400Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  #targetMemoryUtilizationPercentage: 70
